=== Cursedsound/Portfolio1Sem/Portfolio1Semester/src/portfolio/statementOfAccount.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT statementOfAccount (startDate?, meal*, balance?, endDate?)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT meal (purchaseDate+, totalPrice+, item+)>
<!ELEMENT purchaseDate (#PCDATA)>
<!ELEMENT totalPrice (#PCDATA)>
<!ELEMENT item (name, price)*>
<!ATTLIST totalPrice UNIT CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price UNIT CDATA #REQUIRED>
<!ELEMENT balance (#PCDATA)>
<!ATTLIST balance UNIT CDATA #REQUIRED>
<!ELEMENT endDate (#PCDATA)>

=== Cursedsound/Portfolio1Sem/Portfolio1Semester/statementOfAccount.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE statementOfAccount SYSTEM "statementOfAccount.dtd">
<statementOfAccount>
	<startDate>18.1.2022 10:47:11 Uhr</startDate>
	<meal>
		<purchaseDate>18.1.2022</purchaseDate>
		<totalPrice UNIT="euro">7.0</totalPrice>
		<item>
			<name>Pizza</name>
			<price UNIT="euro">5.0</price>
		</item>
		<item>
			<name>Burger</name>
			<price UNIT="euro">2.0</price>
		</item>
	</meal>
	<meal>
		<purchaseDate>18.1.2022</purchaseDate>
		<totalPrice UNIT="euro">9.0</totalPrice>
		<item>
			<name>Salad</name>
			<price UNIT="euro">4.0</price>
		</item>
		<item>
			<name>Pasta</name>
			<price UNIT="euro">5.0</price>
		</item>
	</meal>
	<meal>
		<purchaseDate>18.1.2022</purchaseDate>
		<totalPrice UNIT="euro">-0.41</totalPrice>
		<item>
			<name>Banana</name>
			<price UNIT="euro">0.2</price>
		</item>
		<item>
			<name>Apple</name>
			<price UNIT="euro">0.4</price>
		</item>
		<item>
			<name>Salad</name>
			<price UNIT="euro">4.0</price>
		</item>
		<item>
			<name>Refund</name>
			<price UNIT="euro">-5.0</price>
		</item>
	</meal>
	<meal>
		<purchaseDate>18.1.2022</purchaseDate>
		<totalPrice UNIT="euro">0.0</totalPrice>
		<item>
			<name>Napkins</name>
			<price UNIT="euro">0.0</price>
		</item>
	</meal>
	<balance UNIT="euro">4.4</balance>
	<endDate>18.1.2022 10:47:11 Uhr</endDate>
</statementOfAccount>
